language: node_js
node_js: stable

install:
  - npm install
  - npm install gitbook-cli -g
  - npm install -g gitbook-summary

notifications:
  email:
    - nuxseme@gmail.com
  on_success: always
  on_failure: always

script:
  - gitbook -v
  - gitbook install
  - cd book
  - gitbook build
  - book sm

after_script:
  - cd ./_book
  - ls -al
  - git init
  - git config --global user.name "nuxseme"
  - git config --global user.email "nuxseme@gmail.com"
  - git add .
  - git commit -m "Auto deploy from Travis-CI "
  - git push --force  "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/nuxseme/slim-portal-gitbook.git
